# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend CI

on:
  push:
    branches: [ "master" ]
    paths:
      - '**'
      - '!frontend/**'
      - '!**/.github/workflows/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**'
      - '!frontend/**'
      - '!**/.github/workflows/**'
  workflow_dispatch: 

  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        IMAP_USER: ${{secrets.IMAP_USER}}
        IMAP_PASS: ${{secrets.IMAP_PASS}}
        HOST: ${{secrets.HOST}}
  deploy:
    needs: build
    runs-on: self-hosted
    # Only deploy when code hits the master branch
    if: github.ref == 'refs/heads/master' 
    steps:
      - name: Deploy to Production
        run: |
          cd /home/andrex/shadowmail
          rm -rf node_modules/ package-lock.json
          git pull origin master
          npm install
          sudo systemctl restart shadowmail
  
